language: perl
perl:
  - "5.24"

jdk:
  - openjdk7

addons:
  apt:
    packages:
      - openjdk-7-jdk
      - maven

install:
  - jdk_switcher use openjdk7
  - export PATH=$JAVA_HOME/bin:$PATH
  - export M2_HOME=/usr/share/maven
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | cpan
  - cpan install Carton
  - carton install
  - ./init.sh
  - cd framework/test

jobs:
  include:
    # Test the tutorial and basic commands
    - script: carton exec ./test_tutorial.sh
    - script: carton exec ./test_mutation_analysis.sh
    - script: carton exec ./test_randoop.sh
    - script: carton exec ./test_fix_test_suite.sh
    # Verify that all bugs are reproducible (run multiple jobs for projects that
# take a long time to finish).
    - stage: verify-bugs
## Chart
      script: carton exec ./test_verify_bugs.sh -p Chart
## Closure
    - script: carton exec ./test_verify_bugs.sh -p Closure -b1..10
    - script: carton exec ./test_verify_bugs.sh -p Closure -b11..15
    - script: carton exec ./test_verify_bugs.sh -p Closure -b16..20
    - script: carton exec ./test_verify_bugs.sh -p Closure -b21..30
    - script: carton exec ./test_verify_bugs.sh -p Closure -b31..40
    - script: carton exec ./test_verify_bugs.sh -p Closure -b41..50
    - script: carton exec ./test_verify_bugs.sh -p Closure -b51..60
    - script: carton exec ./test_verify_bugs.sh -p Closure -b61..70
    - script: carton exec ./test_verify_bugs.sh -p Closure -b71..80
    - script: carton exec ./test_verify_bugs.sh -p Closure -b81..90
    - script: carton exec ./test_verify_bugs.sh -p Closure -b91..100
    - script: carton exec ./test_verify_bugs.sh -p Closure -b101..111
    - script: carton exec ./test_verify_bugs.sh -p Closure -b112..122
    - script: carton exec ./test_verify_bugs.sh -p Closure -b123..133
## CommonsCli
    - script: carton exec ./test_verify_bugs.sh -p CommonsCli -b1..12
    - script: carton exec ./test_verify_bugs.sh -p CommonsCli -b13..24
## CommonsCodec
    - script: carton exec ./test_verify_bugs.sh -p CommonsCodec -b1..11
    - script: carton exec ./test_verify_bugs.sh -p CommonsCodec -b12..22
## CommonsCsv
    - script: carton exec ./test_verify_bugs.sh -p CommonsCsc -b1..12
## CommonsJXPath
    - script: carton exec ./test_verify_bugs.sh -p CommonsJXPath -b1..14
## Gson 
    - script: carton exec ./test_verify_bugs.sh -p Gson -b1..8
    - script: carton exec ./test_verify_bugs.sh -p Gson -b9..16
## Guava
    - script: carton exec ./test_verify_bugs.sh -p Guava -b1..4
    - script: carton exec ./test_verify_bugs.sh -p Guava -b5..9
## JacksonCore
    - script: carton exec ./test_verify_bugs.sh -p JacksonCore -b1..13
## JacksonDatabind
    - script: carton exec ./test_verify_bugs.sh -p JacksonDatabind -b1..13
    - script: carton exec ./test_verify_bugs.sh -p JacksonDatabind -b14..26
    - script: carton exec ./test_verify_bugs.sh -p JacksonDatabind -b27..39
## JacksonXml
    - script: carton exec ./test_verify_bugs.sh -p JacksonXml -b1..5
## Jsoup
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b1..10
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b11..20
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b21..30
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b31..41
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b42..52
    - script: carton exec ./test_verify_bugs.sh -p Jsoup -b53..63
## Lang
    - script: carton exec ./test_verify_bugs.sh -p Lang -b1..32
    - script: carton exec ./test_verify_bugs.sh -p Lang -b33..65
## Math
    - script: carton exec ./test_verify_bugs.sh -p Math -b1..18
    - script: carton exec ./test_verify_bugs.sh -p Math -b19..36
    - script: carton exec ./test_verify_bugs.sh -p Math -b20..54
    - script: carton exec ./test_verify_bugs.sh -p Math -b55..80
    - script: carton exec ./test_verify_bugs.sh -p Math -b81..106
## Mockito
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b1..5
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b6..10
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b11..15
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b16..20
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b21..26
    - script: carton exec ./test_verify_bugs.sh -p Mockito -b27..38
## Time
    - script: carton exec ./test_verify_bugs.sh -p Time
